version: '3.8'

services:
  copytop_api:
    build: ./copytop_api/
    ports:
      - "5001:5001"
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    networks:
      - mysql-phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #If you change the credentials in the pma, you need to delete your volumes
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin','ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - mysql-phpmyadmin

volumes:
  dbdata:

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    # use the bridge driver
    driver: bridge
